"""Acronyms: one source for two jobs.

1. extract.py rewrites spelled-out terms in questions and answer choices as
   their acronyms ("Full disk encryption" -> "FDE"), the way the exam itself
   writes them. Only the phrases listed in CONVERT are rewritten, so a phrase
   that is ambiguous or reads badly as an acronym is simply left out.
2. extract.py also writes data/acronyms.js, which the app uses for the
   "Show acronyms" panel under each question.

Expansions follow CompTIA's SY0-701 acronym list where it has the term.
"""

ACRONYMS = {
    "2FA": "Two-factor authentication",
    "AAA": "Authentication, authorization, and accounting",
    "ABAC": "Attribute-based access control",
    "ACL": "Access control list",
    "AES": "Advanced Encryption Standard",
    "AI": "Artificial intelligence",
    "ALE": "Annualized loss expectancy",
    "API": "Application programming interface",
    "APT": "Advanced persistent threat",
    "ARO": "Annualized rate of occurrence",
    "ARP": "Address Resolution Protocol",
    "ASCII": "American Standard Code for Information Interchange",
    "ATT&CK": "Adversarial Tactics, Techniques, and Common Knowledge (MITRE)",
    "AUP": "Acceptable use policy",
    "AV": "Antivirus",
    "BCP": "Business continuity plan",
    "BEC": "Business email compromise",
    "BIA": "Business impact analysis",
    "BIOS": "Basic input/output system",
    "BPA": "Business partners agreement",
    "BSOD": "Blue screen of death",
    "BYOD": "Bring your own device",
    "CA": "Certificate authority",
    "CAB": "Change advisory board",
    "CASB": "Cloud access security broker",
    "CCTV": "Closed-circuit television",
    "CEO": "Chief Executive Officer",
    "CERT": "Computer Emergency Response Team",
    "CFO": "Chief Financial Officer",
    "CHAP": "Challenge Handshake Authentication Protocol",
    "CI/CD": "Continuous integration / continuous delivery",
    "CIA": "Confidentiality, integrity, and availability",
    "CIO": "Chief Information Officer",
    "CIRT": "Computer incident response team",
    "CIS": "Center for Internet Security",
    "CISO": "Chief Information Security Officer",
    "CNAME": "Canonical name (DNS record)",
    "COBO": "Corporate-owned, business only",
    "COOP": "Continuity of operations planning",
    "COPE": "Corporate-owned, personally enabled",
    "CPU": "Central processing unit",
    "CRC": "Cyclic redundancy check",
    "CRL": "Certificate revocation list",
    "CSF": "Cybersecurity Framework (NIST)",
    "CSIRT": "Computer security incident response team",
    "CSO": "Chief Security Officer",
    "CSP": "Cloud service provider",
    "CSR": "Certificate signing request",
    "CSRF": "Cross-site request forgery",
    "CVE": "Common Vulnerabilities and Exposures",
    "CVSS": "Common Vulnerability Scoring System",
    "CYOD": "Choose your own device",
    "DAC": "Discretionary access control",
    "DBA": "Database administrator",
    "DDoS": "Distributed denial of service",
    "DHCP": "Dynamic Host Configuration Protocol",
    "DKIM": "DomainKeys Identified Mail",
    "DLP": "Data loss prevention",
    "DMARC": "Domain-based Message Authentication, Reporting, and Conformance",
    "DNS": "Domain Name System",
    "DNSSEC": "Domain Name System Security Extensions",
    "DoS": "Denial of service",
    "DPO": "Data protection officer",
    "DRP": "Disaster recovery plan",
    "DSS": "Data Security Standard (PCI DSS)",
    "EAP": "Extensible Authentication Protocol",
    "ECC": "Elliptic curve cryptography",
    "EDR": "Endpoint detection and response",
    "EOL": "End of life",
    "EULA": "End-user license agreement",
    "FDE": "Full disk encryption",
    "FIM": "File integrity monitoring",
    "FTP": "File Transfer Protocol",
    "GDPR": "General Data Protection Regulation",
    "GPO": "Group Policy Object",
    "GPS": "Global Positioning System",
    "GRE": "Generic Routing Encapsulation",
    "HA": "High availability",
    "HIDS": "Host-based intrusion detection system",
    "HIPS": "Host-based intrusion prevention system",
    "HR": "Human resources",
    "HSM": "Hardware security module",
    "HSMaaS": "Hardware security module as a service",
    "HTTP": "Hypertext Transfer Protocol",
    "HTTPS": "Hypertext Transfer Protocol Secure",
    "HVAC": "Heating, ventilation, and air conditioning",
    "IaaS": "Infrastructure as a service",
    "IaC": "Infrastructure as code",
    "IAM": "Identity and access management",
    "ICMP": "Internet Control Message Protocol",
    "ICS": "Industrial control system",
    "ID": "Identification",
    "IdP": "Identity provider",
    "IDS": "Intrusion detection system",
    "IEEE": "Institute of Electrical and Electronics Engineers",
    "IM": "Instant messaging",
    "IoC": "Indicator of compromise",
    "IOC": "Indicator of compromise",
    "IoT": "Internet of Things",
    "IP": "Internet Protocol",
    "IPS": "Intrusion prevention system",
    "IPSec": "Internet Protocol Security",
    "IR": "Incident response",
    "IRP": "Incident response plan",
    "ISO": "International Organization for Standardization",
    "ISP": "Internet service provider",
    "IT": "Information technology",
    "JSON": "JavaScript Object Notation",
    "LAN": "Local area network",
    "LDAP": "Lightweight Directory Access Protocol",
    "LDAPS": "Lightweight Directory Access Protocol over SSL",
    "LEAP": "Lightweight Extensible Authentication Protocol",
    "LLM": "Large language model",
    "MAC": "Media access control (hardware address); also mandatory access control",
    "MD5": "Message Digest 5",
    "MDM": "Mobile device management",
    "MFA": "Multifactor authentication",
    "MFD": "Multifunction device",
    "MFP": "Multifunction printer",
    "ML": "Machine learning",
    "MOA": "Memorandum of agreement",
    "MOU": "Memorandum of understanding",
    "MPLS": "Multiprotocol Label Switching",
    "MS-CHAPv2": "Microsoft Challenge Handshake Authentication Protocol version 2",
    "MSA": "Master service agreement",
    "MSP": "Managed service provider",
    "MSSP": "Managed security service provider",
    "MTBF": "Mean time between failures",
    "MTTR": "Mean time to repair",
    "MX": "Mail exchanger (DNS record)",
    "NAC": "Network access control",
    "NAS": "Network-attached storage",
    "NAT": "Network address translation",
    "NDA": "Non-disclosure agreement",
    "NFC": "Near-field communication",
    "NG-SWG": "Next-generation secure web gateway",
    "NGFW": "Next-generation firewall",
    "NIC": "Network interface card",
    "NIDS": "Network-based intrusion detection system",
    "NIPS": "Network-based intrusion prevention system",
    "NIST": "National Institute of Standards and Technology",
    "NTP": "Network Time Protocol",
    "NXDOMAIN": "Non-existent domain (DNS response)",
    "OAuth": "Open Authorization",
    "OCSP": "Online Certificate Status Protocol",
    "OS": "Operating system",
    "OSINT": "Open-source intelligence",
    "OT": "Operational technology",
    "OTP": "One-time password",
    "OVAL": "Open Vulnerability and Assessment Language",
    "OWASP": "Open Worldwide Application Security Project",
    "PaaS": "Platform as a service",
    "PAM": "Privileged access management",
    "PAP": "Password Authentication Protocol",
    "PAT": "Port address translation",
    "PC": "Personal computer",
    "PCAP": "Packet capture",
    "PCI": "Payment Card Industry",
    "PDF": "Portable Document Format",
    "PEAP": "Protected Extensible Authentication Protocol",
    "PED": "Personal electronic device",
    "PEM": "Privacy Enhanced Mail",
    "PHI": "Protected health information",
    "PII": "Personally identifiable information",
    "PIN": "Personal identification number",
    "PKI": "Public key infrastructure",
    "PLC": "Programmable logic controller",
    "PPPoE": "Point-to-Point Protocol over Ethernet",
    "PPTP": "Point-to-Point Tunneling Protocol",
    "PSK": "Pre-shared key",
    "RA": "Registration authority",
    "RADIUS": "Remote Authentication Dial-In User Service",
    "RAID": "Redundant array of independent disks",
    "RAM": "Random access memory",
    "RAS": "Remote access server",
    "RAT": "Remote access Trojan",
    "RBAC": "Role-based access control (also rule-based access control)",
    "RDP": "Remote Desktop Protocol",
    "RFID": "Radio-frequency identification",
    "ROI": "Return on investment",
    "RPO": "Recovery point objective",
    "RSA": "Rivest, Shamir, and Adleman (public key algorithm)",
    "RTO": "Recovery time objective",
    "RTOS": "Real-time operating system",
    "RTP": "Real-time Transport Protocol",
    "S/MIME": "Secure/Multipurpose Internet Mail Extensions",
    "SaaS": "Software as a service",
    "SAE": "Simultaneous Authentication of Equals",
    "SAML": "Security Assertion Markup Language",
    "SAN": "Storage area network",
    "SASE": "Secure access service edge",
    "SCADA": "Supervisory control and data acquisition",
    "SCAP": "Security Content Automation Protocol",
    "SCEP": "Simple Certificate Enrollment Protocol",
    "SD-WAN": "Software-defined wide area network",
    "SDLC": "Software development life cycle",
    "SDN": "Software-defined networking",
    "SFTP": "Secure File Transfer Protocol",
    "SHA": "Secure Hash Algorithm",
    "SIEM": "Security information and event management",
    "SIM": "Subscriber identity module",
    "SIP": "Session Initiation Protocol",
    "SLA": "Service-level agreement",
    "SLE": "Single loss expectancy",
    "SLO": "Service-level objective",
    "SMB": "Server Message Block",
    "SMS": "Short Message Service (text message)",
    "SMTP": "Simple Mail Transfer Protocol",
    "SNMP": "Simple Network Management Protocol",
    "SOAR": "Security orchestration, automation, and response",
    "SOC": "Security operations center",
    "SoC": "System on chip",
    "SOW": "Statement of work",
    "SPF": "Sender Policy Framework",
    "SPIM": "Spam over instant messaging",
    "SQL": "Structured Query Language",
    "SQLi": "SQL injection",
    "SRTP": "Secure Real-time Transport Protocol",
    "SSD": "Solid-state drive",
    "SSH": "Secure Shell",
    "SSID": "Service set identifier",
    "SSL": "Secure Sockets Layer",
    "SSO": "Single sign-on",
    "STIX": "Structured Threat Information eXpression",
    "TACACS": "Terminal Access Controller Access-Control System",
    "TACACS+": "Terminal Access Controller Access-Control System Plus",
    "TCP": "Transmission Control Protocol",
    "TGT": "Ticket-granting ticket (Kerberos)",
    "TLS": "Transport Layer Security",
    "TOC/TOU": "Time of check / time of use",
    "TOTP": "Time-based one-time password",
    "TPM": "Trusted Platform Module",
    "TTP": "Tactics, techniques, and procedures",
    "UAT": "User acceptance testing",
    "UBA": "User behavior analytics",
    "UDP": "User Datagram Protocol",
    "UEM": "Unified endpoint management",
    "UPS": "Uninterruptible power supply",
    "URL": "Uniform Resource Locator",
    "USB": "Universal Serial Bus",
    "UTM": "Unified threat management",
    "VDI": "Virtual desktop infrastructure",
    "VLAN": "Virtual local area network",
    "VM": "Virtual machine",
    "VoIP": "Voice over IP",
    "VPC": "Virtual private cloud",
    "VPN": "Virtual private network",
    "WAF": "Web application firewall",
    "WAN": "Wide area network",
    "WAP": "Wireless access point",
    "WIPS": "Wireless intrusion prevention system",
    "WLAN": "Wireless local area network",
    "WO": "Work order",
    "WPA": "Wi-Fi Protected Access",
    "WPS": "Wi-Fi Protected Setup",
    "XDR": "Extended detection and response",
    "XSS": "Cross-site scripting",
}

# Spelled-out phrases rewritten as the acronym in questions and choices.
# Matching ignores case, treats spaces and hyphens alike, allows a plural
# "s", and swallows a trailing "(ACRONYM)" so "Chief Information Security
# Officer (CISO)" becomes "CISO". Longer phrases are tried first.
CONVERT = {
    "AUP": ["acceptable use policy"],
    "ACL": ["access control list"],
    "ALE": ["annualized loss expectancy"],
    "ARO": ["annualized rate of occurrence"],
    "BEC": ["business email compromise"],
    "BIA": ["business impact analysis"],
    "BYOD": ["bring your own device"],
    "CASB": ["cloud access security broker"],
    "CCTV": ["closed-circuit television"],
    "CEO": ["chief executive officer"],
    "CFO": ["chief financial officer"],
    "CIO": ["chief information officer"],
    "CISO": ["chief information security officer"],
    "COOP": ["continuity of operations planning"],
    "CRL": ["certificate revocation list"],
    "CSR": ["certificate signing request"],
    "CSRF": ["cross-site request forgery"],
    "CVE": ["common vulnerabilities and exposures"],
    "CVSS": ["common vulnerability scoring system"],
    "DDoS": ["distributed denial of service", "distributed denial-of-service"],
    "DLP": ["data loss prevention"],
    "DNS": ["domain name system"],
    "DoS": ["denial of service", "denial-of-service"],
    "DPO": ["data protection officer"],
    "DRP": ["disaster recovery plan"],
    "EDR": ["endpoint detection and response"],
    "EULA": ["end-user license agreement", "end user license agreement"],
    "FDE": ["full disk encryption", "full-disk encryption"],
    "FIM": ["file integrity monitoring"],
    "GDPR": ["general data protection regulation"],
    "GPO": ["group policy object"],
    "HIDS": ["host-based intrusion detection system"],
    "HIPS": ["host-based intrusion prevention system"],
    "HSM": ["hardware security module"],
    "HVAC": ["heating, ventilation, and air conditioning"],
    "IaaS": ["infrastructure as a service"],
    "IaC": ["infrastructure as code"],
    "IAM": ["identity and access management"],
    "ICS": ["industrial control system"],
    "IdP": ["identity provider"],
    "IDS": ["intrusion detection system"],
    "IoT": ["internet of things"],
    "IPS": ["intrusion prevention system"],
    "IRP": ["incident response plan"],
    "ISP": ["internet service provider"],
    "LDAP": ["lightweight directory access protocol"],
    "MDM": ["mobile device management"],
    "MFA": ["multifactor authentication", "multi-factor authentication"],
    "MOA": ["memorandum of agreement"],
    "MOU": ["memorandum of understanding"],
    "MSA": ["master service agreement", "master services agreement"],
    "MSSP": ["managed security service provider"],
    "MTBF": ["mean time between failures", "mean time between failure"],
    "MTTR": ["mean time to repair", "mean time to recovery", "mean time to recover"],
    "NAC": ["network access control"],
    "NAS": ["network-attached storage", "network attached storage"],
    "NAT": ["network address translation"],
    "NDA": ["non-disclosure agreement", "nondisclosure agreement"],
    "NGFW": ["next-generation firewall", "next generation firewall"],
    "NIDS": ["network-based intrusion detection system", "network intrusion detection system"],
    "NIPS": ["network-based intrusion prevention system", "network intrusion prevention system"],
    "OCSP": ["online certificate status protocol"],
    "OS": ["operating system"],
    "OSINT": ["open-source intelligence", "open source intelligence"],
    "OTP": ["one-time password"],
    "PaaS": ["platform as a service"],
    "PAM": ["privileged access management"],
    "PAT": ["port address translation"],
    "PHI": ["protected health information"],
    "PII": ["personally identifiable information"],
    "PKI": ["public key infrastructure"],
    "RDP": ["remote desktop protocol"],
    "RFID": ["radio-frequency identification", "radio frequency identification"],
    "RPO": ["recovery point objective"],
    "RTO": ["recovery time objective"],
    "RTOS": ["real-time operating system", "real time operating system"],
    "SaaS": ["software as a service"],
    "SAML": ["security assertion markup language"],
    "SASE": ["secure access service edge"],
    "SCADA": ["supervisory control and data acquisition"],
    "SCAP": ["security content automation protocol"],
    "SD-WAN": ["software-defined wide area network"],
    "SDLC": ["software development life cycle", "software development lifecycle"],
    "SDN": ["software-defined networking", "software defined networking"],
    "SIEM": ["security information and event management"],
    "SLA": ["service-level agreement", "service level agreement"],
    "SLE": ["single loss expectancy"],
    "SOAR": ["security orchestration, automation, and response"],
    "SOC": ["security operations center"],
    "SOW": ["statement of work"],
    "SQLi": ["sql injection"],
    "SSO": ["single sign-on", "single sign on"],
    "TLS": ["transport layer security"],
    "TOTP": ["time-based one-time password"],
    "TPM": ["trusted platform module"],
    "UAT": ["user acceptance testing"],
    "UBA": ["user behavior analytics"],
    "UEM": ["unified endpoint management"],
    "UPS": ["uninterruptible power supply"],
    "UTM": ["unified threat management"],
    "VDI": ["virtual desktop infrastructure"],
    "VLAN": ["virtual local area network"],
    "VM": ["virtual machine"],
    "VoIP": ["voice over ip"],
    "VPC": ["virtual private cloud"],
    "VPN": ["virtual private network"],
    "WAF": ["web application firewall"],
    "WAP": ["wireless access point"],
    "XDR": ["extended detection and response"],
    "XSS": ["cross-site scripting"],
}

# Acronyms said as a word rather than letter by letter, with the article
# they take ("a SCADA system", "an OSINT tool"). Everything else is spelled
# out, so "an" goes before A E F H I L M N O R S X and "a" before the rest.
SPOKEN = {
    "CASB": "a", "COOP": "a", "COPE": "a", "COBO": "a", "CYOD": "a", "DAC": "a",
    "EULA": "a", "IaaS": "an", "IaC": "an", "IoT": "an", "NAC": "a", "NAT": "a",
    "OSINT": "an", "PaaS": "a", "PAM": "a", "PAT": "a", "RAID": "a", "SaaS": "a",
    "SAML": "a", "SASE": "a", "SCADA": "a", "SCAP": "a", "SIEM": "a", "SOAR": "a",
    "SOC": "a", "SQLi": "an", "VoIP": "a", "VLAN": "a", "WAF": "a", "WAP": "a",
    "UAT": "a", "UBA": "a", "UEM": "a", "UPS": "a", "URL": "a", "USB": "a", "UTM": "a",
}


def article(acr):
    if acr in SPOKEN:
        return SPOKEN[acr]
    return "an" if acr[0].upper() in "AEFHILMNORSX" else "a"
