"""Build js/icons.js and js/art.js from two MIT-licensed icon packages.

    UI icons   Phosphor Icons (duotone, plus fill for active states)
               https://phosphoricons.com  -- npm @phosphor-icons/core
    3D art     Microsoft Fluent Emoji, 3D style (256px WebP)
               https://github.com/microsoft/fluentui-emoji
               -- npm @lobehub/fluent-emoji-3d

Nothing is fetched at run time: the SVG paths and the WebP images are
written into the two modules. To rebuild:

    npm pack @phosphor-icons/core @lobehub/fluent-emoji-3d
    tar -xzf phosphor-icons-core-*.tgz -C phosphor
    tar -xzf lobehub-fluent-emoji-3d-*.tgz -C fluent
    python3 tools/build_icons.py phosphor/package fluent/package
"""

import base64
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# App name -> Phosphor icon.
UI = {
    'study': 'book-open-text',
    'stats': 'chart-bar',
    'review': 'clock-counter-clockwise',
    'saved': 'bookmark-simple',
    'flag': 'flag',
    'build': 'sliders-horizontal',
    'missed': 'arrow-counter-clockwise',
    'target': 'target',
    'timer': 'timer',
    'sun': 'sun',
    'moon': 'moon',
    'left': 'caret-left',
    'right': 'caret-right',
    'check': 'check',
    'x': 'x',
    'similar': 'stack',
    'bulb': 'lightbulb',
    'shield': 'shield-check',
    'back': 'arrow-u-up-left',
    'keyboard': 'keyboard',
    'flame': 'flame',
    'volume': 'speaker-high',
    'mute': 'speaker-slash',
    'smart': 'calendar-check',
    'trophy': 'trophy',
    'clock': 'clock',
    'letters': 'text-aa',
    'search': 'magnifying-glass',
    'empty': 'circle-dashed',
    'verify': 'seal-check',
    'globe': 'globe',
    'sparkle': 'sparkle',
    'video': 'play-circle',
}
# Icons that also ship a filled version (active tab, pressed flag).
FILLED = ['study', 'stats', 'review', 'saved', 'flag']

# App name -> Fluent emoji (codepoints), for the big feature icons.
ART = {
    'build': '1f39b-fe0f',     # control knobs
    'missed': '1f501',         # repeat
    'target': '1f3af',         # direct hit
    'timer': '23f1-fe0f',      # stopwatch
    'search': '1f50d',         # magnifying glass
    'shield': '1f6e1-fe0f',    # shield
    'smart': '1f9e0',          # brain
    'stats': '1f4ca',          # bar chart
    'saved': '1f516',          # bookmark
    'study': '1f4da',          # books
    'trophy': '1f3c6',         # trophy
    'compass': '1f9ed',        # compass
    'calendar': '1f4c5',       # calendar
    'bulb': '1f4a1',           # light bulb
}


def svg_inner(path):
    svg = Path(path).read_text()
    inner = re.search(r'<svg[^>]*>(.*)</svg>', svg, re.S).group(1)
    # The duotone back layer gets a class so CSS can set its strength.
    inner = inner.replace(' opacity="0.2"', ' class="duo"')
    return inner.strip()


def js_string(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def build_icons(phosphor):
    assets = Path(phosphor) / 'assets'
    duo = {k: svg_inner(assets / 'duotone' / f'{v}-duotone.svg') for k, v in UI.items()}
    fill = {k: svg_inner(assets / 'fill' / f'{UI[k]}-fill.svg') for k in FILLED}
    lines = [
        '/**',
        ' * Icons: Phosphor Icons, duotone weight (a filled version too for the',
        ' * active tab and a pressed flag). MIT license, https://phosphoricons.com.',
        ' * Generated by tools/build_icons.py; edit that, not this file.',
        ' *',
        ' * Inline SVG on a 256 grid: crisp at any size, colored by the text color',
        ' * (the soft back layer, class "duo", is the same color at low strength),',
        ' * and no network requests.',
        ' */',
        '',
        'const DUO = {',
        *[f'  {k}: {js_string(v)},' for k, v in duo.items()],
        '};',
        '',
        'const FILL = {',
        *[f'  {k}: {js_string(v)},' for k, v in fill.items()],
        '};',
        '',
        '/** An icon. `weight: "fill"` picks the filled version where there is one. */',
        "export function icon(name, { size = 20, label = '', weight = 'duotone' } = {}) {",
        "  const span = document.createElement('span');",
        "  const filled = weight === 'fill' && FILL[name];",
        "  span.className = `icon icon-${name} w-${filled ? 'fill' : 'duo'}`;",
        "  if (label) { span.setAttribute('role', 'img'); span.setAttribute('aria-label', label); }",
        "  else span.setAttribute('aria-hidden', 'true');",
        '  const body = filled ? FILL[name] : (DUO[name] || DUO.empty);',
        '  span.innerHTML = `<svg viewBox="0 0 256 256" width="${size}" height="${size}" fill="currentColor" focusable="false">${body}</svg>`;',
        '  return span;',
        '}',
        '',
        '/**',
        ' * Both weights side by side; CSS shows the filled one when the control is',
        ' * current or pressed (see .icon-pair in app.css).',
        ' */',
        'export function iconPair(name, opts = {}) {',
        "  const span = document.createElement('span');",
        "  span.className = 'icon-pair';",
        "  span.setAttribute('aria-hidden', 'true');",
        "  span.append(icon(name, opts), icon(name, { ...opts, weight: 'fill' }));",
        '  return span;',
        '}',
        '',
    ]
    (ROOT / 'js' / 'icons.js').write_text('\n'.join(lines))


def build_art(fluent):
    assets = Path(fluent) / 'assets'
    data = {}
    for name, code in ART.items():
        raw = (assets / f'{code}.webp').read_bytes()
        data[name] = 'data:image/webp;base64,' + base64.b64encode(raw).decode()
    lines = [
        '/**',
        ' * 3D art for the big feature icons: Microsoft Fluent Emoji, 3D style.',
        ' * MIT license, https://github.com/microsoft/fluentui-emoji (WebP versions',
        ' * from npm @lobehub/fluent-emoji-3d). Generated by tools/build_icons.py.',
        ' *',
        ' * The images are embedded, so they work offline and need no extra files.',
        ' */',
        '',
        'const ART = {',
        *[f'  {k}: {js_string(v)},' for k, v in data.items()],
        '};',
        '',
        '/** Names of the available art. */',
        'export const ART_NAMES = Object.keys(ART);',
        '',
        '/** A 3D picture (decorative: screen readers skip it). */',
        'export function art(name, { size = 48 } = {}) {',
        "  const img = document.createElement('img');",
        "  img.className = `art art-${name}`;",
        '  img.src = ART[name] || ART.compass;',
        '  img.width = size;',
        '  img.height = size;',
        "  img.alt = '';",
        "  img.decoding = 'async';",
        "  img.draggable = false;",
        '  return img;',
        '}',
        '',
    ]
    (ROOT / 'js' / 'art.js').write_text('\n'.join(lines))


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    build_icons(sys.argv[1])
    build_art(sys.argv[2])
    print('wrote js/icons.js and js/art.js')
